# Define keys
API_KEY = "an api key"
SECRET_KEY = "a secret key"

# Path and file name for the log file
log_path = "data/log-1.txt"

# The name of the assets will be "sold" to by default.
default_sell_to_asset = "USDX"
